services:
  backend:
    build:
      context: ./backend/price_tracker
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./data:/root/data
      # СЛЕДУЮЩАЯ СТРОКА — САМАЯ ВАЖНАЯ:
      - ./backend/price_tracker/.env:/app/.env
    environment:
      - DB_PATH=/root/data/tracker.db
      - GIN_MODE=release
    # env_file можно оставить или удалить, он теперь не критичен
    env_file:
      - ./backend/price_tracker/.env

  frontend:
    build: 
      context: ./frontend/price-tracker
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend