services:
  backend:
    build:
      context: ./backend/price_tracker
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./data:/root/data
      - ./backend/price_tracker/.env:/root/.env:ro
      - ./backend/price_tracker/.env:/app/.env:ro
    environment:
      DB_PATH: /root/data/tracker.db
      GIN_MODE: release
    env_file:
      - ./backend/price_tracker/.env

  frontend:
    restart: always
    build: 
      context: ./frontend/price-tracker
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend